name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.5.0
homepage: https://github.com/pulyaevskiy/test-coverage
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  test_coverage:

dependencies:
  cli_util: ^0.3.5
  coverage: ^1.0.3
  path: ^1.8.1
  lcov_dart: ^7.0.0
  glob: ^2.0.1
  args: ^2.3.0

dev_dependencies:
  test: ^1.17.12
  pedantic: ^1.11.1

